### ISSUE TITLE
How to make category main page(or tag page)?

### ISSUE THREAD

**Issue by shldhee** [henryhuang/oishi#14]
I want to access to the categories(category page) from the menu. It's my choice !
When I clicked LIFE, TAG menu, it opened 404 page.

Do you have category form(index.html)?

This is my blog url. - https://shldhee.github.io

**Comment by henryhuang** [comment]
@shldhee Sorry, it need you to create a post which tag contain LIFE, and re-generate the site, it will generate the LIFE tag page.
