### ISSUE TITLE
你好，为什么和demo的效果不一样呢

### ISSUE THREAD

**Issue by tangxiaolang101** [henryhuang/oishi#3]
为什么和这个网站http://www.cnhalo.com/的效果不一样呢

**Comment by henryhuang** [comment]
@tangxiaolang101 不好意思，看你的回复，你这个时间点看到的页面，我当时已经用了其他的主题了（Next主题，用的人蛮多的）。你这样也刚好提醒了我，得专门弄个website来展示这个主题，谢谢！近期我会提供。

**Comment by henryhuang** [comment]
@tangxiaolang101 我新加了个demo page，https://henryhuang.github.io/oishi/ ，
以后以这个为准
