### ISSUE TITLE
 WARN  No layout: index.html

### ISSUE THREAD

**Issue by q27488** [henryhuang/oishi#7]
当我把theme 设置成 oishi， hexo s开启服务，打开 localhost:4000 页面空白，浏览器也没报错，node报错如题。

**Comment by henryhuang** [comment]
@q27488 ，可能是你的source _post 里有一些文本编辑器的临时文件，比如 sublime 编辑 markdown 的时候会生成，我以前遇到过是这个原因，删了就好。但是我不知道你是不是因为这个，你现在解决了吗？

**Comment by henryhuang** [comment]
@q27488 Hi，如果没问题的话我就关闭了哦
